name: build project

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'master'

jobs:
  build_and_test:
    name: 'Build & Test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore -s https://api.nuget.org/v3/index.json
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --verbosity normal --logger "trx;LogFileName=test-results.trx" MiHomeUnitTests
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success()
      with:
        name: xUnit Tests
        path: MiHomeUnitTests/TestResults/test-results.trx
        reporter: dotnet-trx
    - name: Get test report results
      run: echo "PASSED=$(cat MiHomeUnitTests/TestResults/test-results.trx | grep passed | awk '{print $4}' | awk -F= '{print $2}' | sed "s/\"//g")" >> $GITHUB_ENV 
    - name: Print test results
      run: echo ${{ env.PASSED }}
